language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package
  - ./analyse-pull-request.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false