language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script:
  - mvn clean package
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && echo "=============> Pull request is ${TRAVIS_PULL_REQUEST}"'

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false